<a href="https://colab.research.google.com/github/kanri3/applied_math/blob/main/Applied_Math_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##☆第2章:確率・統計  
###1. 条件付き確率とは？  
事象X=xを前提に事象Y=yが生じる確率。  
ここでX,Yは「ある系」（サイコロ，天気etc）を表し、またx,yはその系の下で起きる事象を表す。
###2. ベイズの定理とは？  
たとえばワクチン接種をすると安心顔になる確率が既知であるなら、ベイズ則により安心顔の人がワクチン接種を済ましている確率を求められる。  
（但し、ワクチン接種を受けられる確率および安心顔である確率が既知であること）  
###3. 期待値とは？  
いわゆる平均値。
確率変数と確率の積を全ての事象について合計したもの。  
###4. 分散とは？  
分散とは、データの散らばり具合を表す値である。  
データの正負が原因で生じる相殺を回避する処理（二乗）の後、平均をとったもの。  
###5. 様々な確率分布の概要を知る。


In [1]:
import numpy as np

In [ ]:
m=np.array([[1,2,0],[0,1,0],[0,0,1]])
m

array([[1, 2, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
h=np.array([[1,1],[1,-1/2]])
j=np.linalg.inv(h)
j

array([[ 0.33333333,  0.66666667],
       [ 0.66666667, -0.66666667]])

In [ ]:
g=np.array([[5,0],[0,-1]])
c=h.dot(g).dot(j)
c

array([[1., 4.],
       [2., 3.]])

In [ ]:
t=0
f=2
p=np.array([[1,t,0],[0,f,0],[0,0,3]])
p

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
r=np.array([[1,-2,0],[0,1,0],[0,0,1]])
r

array([[ 1, -2,  0],
       [ 0,  1,  0],
       [ 0,  0,  1]])

In [ ]:
y=m.dot(p).dot(r)
y

array([[1, 2, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
t=4
w=np.array([[1,-1/t],[0,1/t]])
z=y.dot(w)
z

array([[2., 1.],
       [0., 6.]])

In [ ]:
a=np.array([[3,2,0],[0,2,0],[0,0,1]])
a

array([[3, 2, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [ ]:
np.linalg.eigvals(a)
np.linalg.eig(a)

(array([3., 2., 1.]), array([[ 1.        , -0.89442719,  0.        ],
        [ 0.        ,  0.4472136 ,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]))

In [ ]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train.ndim

11501568/11490434 [==============================] - 0s 0us/step


3

In [ ]:
import pandas as pd

In [ ]:
data=pd.DataFrame({
    "col1":[1,2,None,np.nan],
    "col2":[1.2,2.3,None,np.nan],
    "col3":['aaa','bbb',None,np.nan],
})
data

col1  col2  col3
0   1.0   1.2   aaa
1   2.0   2.3   bbb
2   NaN   NaN  None
3   NaN   NaN   NaN

In [ ]:
data.isna()

col1   col2   col3
0  False  False  False
1  False  False  False
2   True   True   True
3   True   True   True

In [ ]:
s=pd.Series([3,2,3,2,2])
s2=pd.Series([2,4,6,8,10])
s

0    3
1    2
2    3
3    2
4    2
dtype: int64

In [ ]:
s2

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
df=pd.concat([s,s2],axis=1)
df

0   1
0  3   2
1  2   4
2  3   6
3  2   8
4  2  10

In [ ]:
type(df)

pandas.core.frame.DataFrame